//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pay"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="SalaryCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MinimumSalary" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MaximumSalary" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DisplaySalary" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pay", propOrder = {

})
public class Pay
    implements Serializable
{

    @XmlElement(name = "SalaryCurrency", required = true)
    protected String salaryCurrency;
    @XmlElement(name = "MinimumSalary", required = true)
    protected String minimumSalary;
    @XmlElement(name = "MaximumSalary", required = true)
    protected String maximumSalary;
    @XmlElement(name = "DisplaySalary", required = true)
    protected String displaySalary;

    /**
     * Gets the value of the salaryCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalaryCurrency() {
        return salaryCurrency;
    }

    /**
     * Sets the value of the salaryCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalaryCurrency(String value) {
        this.salaryCurrency = value;
    }

    /**
     * Gets the value of the minimumSalary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumSalary() {
        return minimumSalary;
    }

    /**
     * Sets the value of the minimumSalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumSalary(String value) {
        this.minimumSalary = value;
    }

    /**
     * Gets the value of the maximumSalary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumSalary() {
        return maximumSalary;
    }

    /**
     * Sets the value of the maximumSalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumSalary(String value) {
        this.maximumSalary = value;
    }

    /**
     * Gets the value of the displaySalary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplaySalary() {
        return displaySalary;
    }

    /**
     * Sets the value of the displaySalary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplaySalary(String value) {
        this.displaySalary = value;
    }

}
