package com.talentPool.customReports.dataobject;

// Generated Mar 12, 2012 2:51:04 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CRReportTypes generated by hbm2java
 */
@Entity
@Table(name = "tp_cr_report_types")
public class CRReportTypes implements java.io.Serializable {

	private long crReportTypeId;
	private String crReportTypeName;
	private String crReportTypeKindId;
	private Set<CRReportTypeColumnMapping> crReportTypeColumnMapping = new HashSet<CRReportTypeColumnMapping>(0);

	public CRReportTypes() {
	}

	public CRReportTypes(long crReportTypeId, String crReportTypeName,
			String crReportTypeKindId) {
		this.crReportTypeId = crReportTypeId;
		this.crReportTypeName = crReportTypeName;
		this.crReportTypeKindId = crReportTypeKindId;
	}

	public CRReportTypes(long crReportTypeId, String crReportTypeName,
			String crReportTypeKindId,
			Set<CRReportTypeColumnMapping> crReportTypeColumnMapping) {
		this.crReportTypeId = crReportTypeId;
		this.crReportTypeName = crReportTypeName;
		this.crReportTypeKindId = crReportTypeKindId;
		this.crReportTypeColumnMapping = crReportTypeColumnMapping;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "cr_report_type_id", unique = true, nullable = false)
	public long getCrReportTypeId() {
		return this.crReportTypeId;
	}

	public void setCrReportTypeId(long crReportTypeId) {
		this.crReportTypeId = crReportTypeId;
	}

	@Column(name = "cr_report_type_name", nullable = false, length = 250)
	public String getCrReportTypeName() {
		return this.crReportTypeName;
	}

	public void setCrReportTypeName(String crReportTypeName) {
		this.crReportTypeName = crReportTypeName;
	}

	@Column(name = "cr_report_type_kind_id", nullable = false, length = 2)
	public String getCrReportTypeKindId() {
		return this.crReportTypeKindId;
	}

	public void setCrReportTypeKindId(String crReportTypeKindId) {
		this.crReportTypeKindId = crReportTypeKindId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "crReportTypes")
	public Set<CRReportTypeColumnMapping> getCRReportTypeColumnMapping() {
		return this.crReportTypeColumnMapping;
	}

	public void setCRReportTypeColumnMapping(
			Set<CRReportTypeColumnMapping> crReportTypeColumnMapping) {
		this.crReportTypeColumnMapping = crReportTypeColumnMapping;
	}
}