use talentpool;

insert into `tp_source_types` (source_type,	system_generated, source_type_category)
values ('Candidate Portal',1, 5);
insert into `tp_sources` ( source_type_id, source_title, source_email, source_phone, source_mobile, 
is_send_email_to_source, is_send_sms_to_source, lock_in_period_on_import, source_status, system_generated)
values((select source_type_id from tp_source_types where source_type_category = 5 limit 0, 1),'Candidate Portal','','','',0,0, 0,1,1);
insert into `tp_application_properties`(`application_property`,`application_property_value`) values ( 'default_position_approval_duration','2');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '60','1');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '60','2');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '60','13');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '60','18');
insert into `tp_template_types`(`template_type_id`,`template_type`) values ( '60','Requisition approval pending mail notification to HR manager');
insert into `tp_templates`(`template_id`,`template_code`,`template_name`,`template_subject_file`,`template_content_file`,`template_auto`,`template_format`,`template_private`,`template_type_id`,`template_is_default`,`template_date_created`,`template_is_save_as_draft`,`do_show_save_as_draft_option`,`user_id`,`is_repeat`) values ( '129','requisitionApprovalPendingnotificationToHrmanager','requisitionApprovalPendingnotificationToHrmanager','requisitionApprovalPendingnotificationToHrmanagerSubject.vm','requisitionApprovalPendingnotificationToHrmanagerContent.vm','0','0','0','60','1','2016-03-09 11:10:15','0','0','1','0');
insert into `tp_templates`(`template_id`,`template_code`,`template_name`,`template_subject_file`,`template_content_file`,`template_auto`,`template_format`,`template_private`,`template_type_id`,`template_is_default`,`template_date_created`,`template_is_save_as_draft`,`do_show_save_as_draft_option`,`user_id`,`is_repeat`) values ( '130','positionDuplicateAlertNotificationToAdmin','positionDuplicateAlertNotificationToAdmin Email','positionDuplicateAlertNotificationToAdminSubject.vm','positionDuplicateAlertNotificationToAdminContent.vm','0','0','0','61','1','2016-03-09 11:12:15','0','0','1','0');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '61','1');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '61','2');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '61','13');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '61','18');
insert into `tp_template_types`(`template_type_id`,`template_type`) values ( '61','position duplicate alert notification to admin');
insert into `tp_position_approval_scheduler`(`scheduler_id`,`scheduler_name`,`scheduler_start_hour`,`scheduler_frequency`,`last_run_status`,`last_run_starttime`,`last_run_endtime`,`last_success_run`,`current_status`) values ( '1','position approval scheduler',NULL,'8','0',NULL,NULL,NULL,'0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '1','43','0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '2','43','0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '3','43','0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '4','43','0');
insert into `tp_application_properties`(`application_property`,`application_property_value`) values ( 'send_mail_to_Hrmanager_Pending_Requisition_approval','1');
insert into `tp_application_properties`(`application_property`,`application_property_value`) values ( 'autoApproveRequisition','1');
insert into `tp_application_properties`(`application_property`,`application_property_value`) values ( 'duplicatePositionAlertNotificationToAdmin','1');



insert into `tp_template_types`(`template_type_id`,`template_type`) values ( '62','Candidate profile Update Template');

insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '62','3');

insert into `tp_template_types`(`template_type_id`,`template_type`) values ( '63','Candidate Position Applied Template');

insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '63','3');
insert into `tp_template_vars`(`template_type_id`,`template_variable_type`) values ( '63','14');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '1','45','0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '2','45','0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '3','45','0');
insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '4','45','0');

create temporary table if not exists tp_temp_3 as (select field_rank+1 FROM (SELECT max(field_rank) as field_rank FROM tp_screen_configurations) AS x);
INSERT INTO tp_screen_configurations 
	(field_id, field_type, is_process_field, field_rank, field_import_show, field_edit_show, 
	field_import_mandatory, field_confidential, field_vendor_show, field_vendor_mandatory, 
	field_employee_show, field_employee_mandatory, field_applicant_show_on_site, 
	field_applicant_mandatory_on_site) 
VALUES ('ApplicantResumePath','0','0',(select * from tp_temp_3),'0','0','0','0','0','0','0','0','1','0');
drop table tp_temp_3;

insert into `tp_report_levels`(`level_id`,`report_id`,`report_type`) values ( '1','33','0');

INSERT INTO tp_user_scheduler (scheduler_name, scheduler_start_hour, scheduler_frequency) 
VALUES ('User Scheduler', 22, 24);

INSERT INTO tp_template_generic_vars (template_variable_type,template_variable)
VALUES (25,'QUESTIONNAIRE_DETAILS');

INSERT INTO tp_template_vars (template_type_id, template_variable_type)
VALUES (25,25);

INSERT INTO tp_users (USER_ID,USER_NAME,USER_FNAME,USER_PASSWORD,USER_EMAIL,USER_STATUS) VALUES
(-1,'Applicant','Applicant','601F1889667EFAEBB33B8C12572835DA3F027F78','system','0');

UPDATE tp_permissions set permission_desc = 'Custom Fields'
where permission_id = 69;

UPDATE tp_permissions set permission_desc = 'Label Messages'
where permission_id = 70;


insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('1','Name','0',NULL,NULL,NULL,NULL,'Applicant Name',NULL,'','1','Name','applicantName',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('2','City','0',NULL,NULL,NULL,NULL,'Applicant City',NULL,'','1','CurrentLocation','applicantCity',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('3','Skills','4',NULL,NULL,NULL,NULL,'Skill','/masters/skills','','1','Skills','skillsString',NULL,'Skill','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('4','Employer','3',NULL,NULL,NULL,NULL,'Company Name','/masters/employers','','1','Employment History','employerName','8','Employer','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('5','Designation','3',NULL,NULL,NULL,NULL,'Designation','/masters/designation','','1','Employment History','designationName','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('6','From Date','2',NULL,NULL,NULL,NULL,'YYYY-MM-DD',NULL,'left','1','Employment History','employerFromDate','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('7','To Date','2',NULL,NULL,NULL,NULL,'YYYY-MM-DD',NULL,'right','1','Employment History','employerToDate','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('8','Add Employment History','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','Employment History','',NULL,'ApplicantEmploymentHistory','-1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('9','Contact','0','^[0-9]{10}$','Contact should be 10 digit numeric mobile number',NULL,NULL,'Enter 10 digigt mobile number',NULL,NULL,'1','Mobile','applicantCellPhone',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('10','Email','0','^[a-z]+[a-z0-9._]+@[a-z]+\\.[a-z.]{2,5}$','Email should contain valid email id',NULL,NULL,'Email',NULL,NULL,'1','Email1','applicantEmail1',NULL,'Applicant','2','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('11','Education','7',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','Education',NULL,NULL,'ApplicantEducationalInfo','-1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('12','Degree','3',NULL,NULL,NULL,NULL,NULL,'/masters/degrees',NULL,'1','Education','degreeTitle','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('13','Year','8',NULL,NULL,'1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015',NULL,NULL,NULL,NULL,'1','Education','yearOfPassing','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('14','Institute','3',NULL,NULL,NULL,NULL,NULL,'/masters/institutes',NULL,'1','Education','institute','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('15','Grade','0',NULL,NULL,NULL,NULL,NULL,NULL,'left','1','Education','grade','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('16','Branch','3',NULL,NULL,NULL,NULL,NULL,'/masters/branches',NULL,'1','Education','major','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('17','Position Name','0',NULL,NULL,NULL,NULL,NULL,NULL,'right','2','PositionName','name',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('18','Location','4',NULL,NULL,NULL,NULL,NULL,'/master/location',NULL,'2','Location','locations',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('19','Grade','3',NULL,NULL,NULL,NULL,NULL,'/master/grades','left','2','Grade','budgetGrade',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('20','Vacancies','1',NULL,NULL,NULL,NULL,NULL,NULL,'right','2','Vacancies','noOfOpenings',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('21','Note','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','Note','note',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('22','Primary Skills','4',NULL,NULL,NULL,NULL,NULL,'/master/skills-category',NULL,'2','PrimarySkills','positionSkills',NULL,'Skill','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('23','Secondary Skills','4',NULL,NULL,NULL,NULL,NULL,'/master/skills-category',NULL,'2','SecondarySkills','positionSkills',NULL,'Skill','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('24','Max Experience','1',NULL,NULL,'0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32',NULL,NULL,NULL,'left','2','Experience','maxExp',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('25','Min Experience','1',NULL,NULL,'0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32',NULL,NULL,NULL,'right','2','Experience','minExp',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('26','Band','3',NULL,NULL,NULL,NULL,NULL,'/master/bands','right','2','BudgetBand','budgetBand',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('27','Position Level','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','PositionLevel','level',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('28','Referals fees','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','ReferalFees','referalFees',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('29','Type of vacancy','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','TypeOfVacancies','typeOfVacancy',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('30','Branch','3',NULL,NULL,NULL,NULL,NULL,'/master/branches','right','2','Branch','branch',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('31','Degree','3',NULL,NULL,NULL,NULL,NULL,'/master/degrees','left','2','Education','degree',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('32','Detail Job Description','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','Responsibilities','responsibilities',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('33','Position code','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','PositionCode','code',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('34','Requested By','11',NULL,NULL,NULL,NULL,NULL,'/master/users',NULL,'2','RequestedBy','requestedBy',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('35','Position Priority','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','PositionPriority','priority',NULL,'Position','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('36','Attach Documents','9',NULL,NULL,NULL,NULL,NULL,'/requisition/document',NULL,'2','PositionDocument','positionDocuments',NULL,'Position','-1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('37','File Name','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','DocumentName','fileName','36','PositionDocument','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('38','Date','2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','DocumentDate','dateCreated','36','PositionDocument','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('39','Download','10',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','DocumentDownload','documentPath','36','PositionDocument','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('40','Email2','0','^[a-z]+[a-z0-9._]+@[a-z]+\\.[a-z.]{2,5}$','Email should contain valid email id',NULL,NULL,'Email',NULL,NULL,'1','Email2','applicantEmail2',NULL,'Applicant','2','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('41','Applicant Id','0',NULL,NULL,NULL,NULL,'Applicant Id',NULL,'','1','Applicant Id','applicantId',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('42','From Year','8',NULL,NULL,'1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015',NULL,NULL,NULL,NULL,'1','Education','fromYear','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('43','Remarks','15',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','Education','remarks','11','ApplicantEducationalInfo','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('44','Reason For Leaving','15',NULL,NULL,NULL,NULL,'Reason For Leaving',NULL,'','1','Employment History','reasonForLeaving','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('45','Duties Involved','15',NULL,NULL,NULL,NULL,'Duties Involved',NULL,'','1','Employment History','dutiesInvolved','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('46','Gross Salary','0',NULL,NULL,NULL,NULL,'Gross Salary',NULL,'','1','Employment History','grossSalary','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('47','Allowance','0',NULL,NULL,NULL,NULL,'Allowance',NULL,'','1','Employment History','allowance','8','ApplicantEmploymentHistory','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('48','Experience','0',NULL,NULL,NULL,NULL,'Applicant Experience',NULL,'','1','Experience','applicantWorkingSince',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('49','Date Of Birth','2',NULL,NULL,NULL,NULL,'dd/MM/yyyy',NULL,'','1','DateOfBirth','dateOfBirth',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('50','Current CTC','0',NULL,NULL,NULL,NULL,'Current CTC',NULL,'','1','CurrentCTC','currentCTC',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('51','Expected CTC','0',NULL,NULL,NULL,NULL,'Expected CTC',NULL,'','1','ExpectedCTC','expectedCTC',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('52','Notice Period','1',NULL,NULL,NULL,NULL,'Notice Period',NULL,'','1','NoticePeriod','noticePeriod',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('53','NRIC/Passport Number','0',NULL,NULL,NULL,NULL,'Passport Number',NULL,'','1','PassportNumber','passportNumber',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('55','Home Phone','0','^[0-9]$','Home Phone should be numeric',NULL,NULL,'Home Phone',NULL,NULL,'1','Phone1','applicantHomePhone',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('56','Work Phone','0','^[0-9]$','Work Phone should be numeric',NULL,NULL,'Work Phone',NULL,NULL,'1','Phone2','applicantWorkPhone',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('57','Resume Type','3',NULL,NULL,NULL,NULL,'Resume Type','/masters/resumeTypes','','1','ResumeType','resumeType',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('58','Current Employer','0',NULL,NULL,NULL,NULL,'Current Employer',NULL,'','1','CurrentEmployer','applicantCurrentEmployer',NULL,'Applicant','1','1');
insert into `tp_dynamic_field` (`id`, `display_name`, `field_type`, `regex`, `regex_message`, `option_list`, `default_value`, `watermark_placeholder`, `api_url`, `css_class_name`, `entity_type`, `reference_field_id`, `property_name`, `parent_id`, `entity_name`, `no_of_rows`, `is_required`) values('59','Note','0',NULL,NULL,NULL,NULL,'Note',NULL,NULL,'1','Note','note',NULL,'Applicant','1','1');

update tp_screen_configurations set field_applicant_show_on_site=0 where field_id = 'Source';
update `tp_dynamic_field` set `regex`='^([1-9]([0-9]{9})|[+]([0-9]{12}))$' where id in (9,55,56);
update `tp_dynamic_field` set `regex_message`='Contact should be 10 digit numeric mobile number or 13 digit number(including country code with + sign)' where id=9;
update `tp_dynamic_field` set `regex_message`='Home Phone should be 10 digit number or 13 digit number(including country code with + sign)' where id=55;
update `tp_dynamic_field` set `regex_message`='Work Phone should be 10 digit number or 13 digit number(including country code with + sign)' where id=56;

insert into tp_report_levels values('1', '46', '0');
insert into tp_report_levels values('1', '47', '0');
insert into tp_user_permissions(user_id,permission_id) select user_id,101 from tp_user_roles where role_id=1;
insert into tp_role_permissions values(1,101);