/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_talentPool_jni_WordJNI */

#ifndef _Included_com_talentPool_jni_WordJNI
#define _Included_com_talentPool_jni_WordJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_talentPool_jni_WordJNI
 * Method:    convertWordToHtml
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_talentPool_jni_WordJNI_convertWordToHtml
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
