package com.talentPool.masters.dataobject;
// Generated Apr 26, 2012 2:09:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TpEmployerAliasesId generated by hbm2java
 */
@Embeddable
public class EmployerAliasesId implements java.io.Serializable {

	private long employerId;
	private String alias;

	public EmployerAliasesId() {
	}

	public EmployerAliasesId(long employerId, String alias) {
		this.employerId = employerId;
		this.alias = alias;
	}

	@Column(name = "employer_id", nullable = false)
	public long getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(long employerId) {
		this.employerId = employerId;
	}

	@Column(name = "alias", unique = true, nullable = false, length = 150)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployerAliasesId))
			return false;
		EmployerAliasesId castOther = (EmployerAliasesId) other;

		return (this.getEmployerId() == castOther.getEmployerId())
				&& ((this.getAlias() == castOther.getAlias()) || (this
						.getAlias() != null && castOther.getAlias() != null && this
						.getAlias().equals(castOther.getAlias())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getEmployerId();
		result = 37 * result
				+ (getAlias() == null ? 0 : this.getAlias().hashCode());
		return result;
	}

}
