package com.talentPool.masters.dataobject;
// Generated Apr 26, 2012 2:09:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TpDesignationsAliasesId generated by hbm2java
 */
@Embeddable
public class DesignationAliasesId implements java.io.Serializable {

	private long designationId;
	private String alias;

	public DesignationAliasesId() {
	}

	public DesignationAliasesId(long designationId, String alias) {
		this.designationId = designationId;
		this.alias = alias;
	}

	@Column(name = "designation_id", nullable = false)
	public long getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(long designationId) {
		this.designationId = designationId;
	}

	@Column(name = "alias", unique = true, nullable = false, length = 150)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DesignationAliasesId))
			return false;
		DesignationAliasesId castOther = (DesignationAliasesId) other;

		return (this.getDesignationId() == castOther.getDesignationId())
				&& ((this.getAlias() == castOther.getAlias()) || (this
						.getAlias() != null && castOther.getAlias() != null && this
						.getAlias().equals(castOther.getAlias())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getDesignationId();
		result = 37 * result
				+ (getAlias() == null ? 0 : this.getAlias().hashCode());
		return result;
	}

}
