#Other db settings
other.db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
other.db.url=jdbc:sqlserver://localhost:1433;DatabaseName=talentpool_1110
other.db.username=sa
other.db.password=N!tm@n

#CONNECTION POOL PROPERTIES
other.db.pool.initial_connections=10
other.db.pool.max_connections=20
other.db.pool.wait_if_busy=true


#Mysql db#
#other.db.driver=com.mysql.jdbc.Driver
#other.db.url=jdbc:mysql://localhost:3306/tp_12_2
#other.db.username=root
#other.db.password=N!tm@n

# Talentpool Link For Greytip Integration
talentpool.url=http://localhost:9090/TalentPool/

#Scheduler frequency for moving joined candidate to greytip
greytip.getdata.scheduler_frequency.minutes=5
greytip.postdata.scheduler_frequency.minutes=5

#
xml.greytip.sql.dir=others/integration/
xml.greytip.column_map.file=GREYTIP_FIELD_MAP_XML.xml

greytip.db.insert_table_name=import_data_dump
greytip.db.fetch_table_name=import_data_dump


thyssenkrupp.custom_field.registration_no=0
