package com.talentPool.customReports.dataobject;

// Generated Jan 5, 2012 7:05:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CrFilters generated by hbm2java
 */
@Entity
@Table(name = "tp_cr_filters")
public class CRFilters implements java.io.Serializable {

	private Integer filterId;
	private String filterName;
	private Set<CRColumnFilterMap> crColumnFilterMaps = new HashSet<CRColumnFilterMap>(0);

	public CRFilters() {
	}

	public CRFilters(String filterName) {
		this.filterName = filterName;
	}

	public CRFilters(String filterName,Set<CRColumnFilterMap> crColumnFilterMaps) {
		this.filterName = filterName;
		this.crColumnFilterMaps = crColumnFilterMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "filter_id", unique = true, nullable = false)
	public Integer getFilterId() {
		return this.filterId;
	}

	public void setFilterId(Integer filterId) {
		this.filterId = filterId;
	}

	@Column(name = "filter_name", nullable = false, length = 50)
	public String getFilterName() {
		return this.filterName;
	}

	public void setFilterName(String filterName) {
		this.filterName = filterName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CRFilters")
	public Set<CRColumnFilterMap> getCrColumnFilterMaps() {
		return this.crColumnFilterMaps;
	}

	public void setCrColumnFilterMaps(Set<CRColumnFilterMap> crColumnFilterMaps) {
		this.crColumnFilterMaps = crColumnFilterMaps;
	}

}
