########## This Property File Contains the Reg Expression used in parsing the Resume got from Monster. ##########

########## Used to parse the phone Numbers
part1 		= (?mids)(Phone:.*)
part11 		= (?mids)(Mobile.*)

########## Used to parse the Source
part15 		= monster

########## Used to parse the Skills

########## Used to parse the Education Details
part12 		= (?mids)(Highest Degree Held.*)
part13 		= 2nd Highest Degree Held
part14 		= Preferred Job Location
part17 		= (?mids)(.*?2nd Highest Degree Held)

########## Used to parse the Current CTC
part6 		= (?mids)(Current Annual Salary.*)

########## Used to parse the Working Experience
part7 		= (?mids)(Work Experience.*)

########## Used to parse the Email
part2 		= (?mids)(Email:.*)

########## Used to parse the Name
part3 		= (?mids)(Contact Information.*)
part31 		= (?mids)(Include Resume Summary.*)
part4 		= Date of Birth:

########## Used to parse the Current Employer
part9 		= (?mids)(Current Employer.*)

########## Used to parse the Current Location
part10 		= (?mids)(Current Location:.*)

part18 = "(?mids)(Previous Employer.*)";
monsterFormatexp = "(?mids)(Source Monster.*)(Highest Education.*)(Authorization US.*)(US Military Service.*)";
regexEmail = "(?mids)[a-z0-9.\\-_]+@([a-z0-9\\-_]+\\.)+(" + "com|net|org|edu|int|mil|gov|arpa|biz|" + "aero|name|coop|info|pro|museum|tv|([a-z]{2}))";
	private static final String regexMobile="[\\s](\\({0,1}\\d{3}\\){0,1}" +
			"[- \\.]\\d{3}[- \\.]\\d{4})|" +
			"(\\+\\d{2}-\\d{2,4}-\\d{3,4}-\\d{3,4})";
part19 = "(?mids)(View candidate(.+?)PrintÂ )";
part20 = "(?mids)(PrintÂ.*)";