########## This Property File Contains the Reg Expression used in parsing the Resume got from TimesJobs. ##########
timesjobsFormatExp 	=timesjobs

########## Used to parse Applicant Name ########## 
part4 =(?mids)(Download Resume.*)

########## Used to parse Applicant Email and phone number ##########
part1 =(?mids)(Phone:.*)
part2 =(?mids)(Mobile.*)


########## Used to parse Source ##########
part12 =(?mids)(Times\\s*Job*)


########## Used to parse location ##########
part7 =(?mids)(Current Location:.*)
part11 =(?mids)(Current Location :.*)

########## Used to parse Education Detils ##########
part14 =(?mids)(Educational Information.*)
part15 =Candidate Resume
part16 =Highest Qualification
part17 =2nd Highest


########## Used to parse Work Experience ##########
part8 =(?mids)(Work Experience.*)
part18 =Fresher

########## Used to parse Current Employer ##########
part6 =(?mids)(Current Employer:.*)
part13 =(?mids)(Current Employer.*)	

########## Used to parse Current CTC ##########
part10 =Rs.

########## Used to parse Salary ##########
part9 =(?mids)(Salary:.*)

part5 =(?mids)(Forward.*)