#This is same as you give in connection settings
ExchangeServer=mail.xyz.exchange.ms
ExchangePath=exchange
#This is same as you give in microsoft exchange server
MailServer=xyz.mse6.exchange.ms
DestinationAddress=jobs.mindteck@mindteck.com
Username=jobs.mindteck
Password=jobs@321
#domain is same as MailServer
Domain=xyz.mse6.exchange.ms
#path where talentpool is installed
MboxFile=c:/Program files/TalentPool/email.mbox
Delete=true
All=false
Secure=true
#Chnage following if required only
FBApath=/exchweb/bin/auth/owaauth.dll
ForceFrom=false
ForceFromAddr=fake.sender@yyy.dddddd.com
NoEightBitMime=false
