DELETE FROM tp_custom_field_values_applicant;
DELETE FROM tp_applicant_educational_info;
DELETE FROM tp_applicant_flags;
DELETE FROM tp_applicant_joining_history;
DELETE FROM tp_applicant_status_messages;
DELETE FROM tp_applicant_skills;
DELETE FROM tp_todo;
DELETE FROM tp_applicant_selection_process_traits;
DELETE FROM tp_applicant_selection_process;
DELETE FROM tp_appointment_attendees;
DELETE FROM tp_appointments_notifications;
DELETE FROM tp_appointments;
DELETE FROM tp_communications;

DELETE FROM tp_user_activity;
DELETE FROM tp_position_skills;
DELETE FROM tp_position_step_status_messages;
DELETE FROM tp_position_step_users;
DELETE FROM tp_position_steps;
DELETE FROM tp_requisition_approval_feedback;
DELETE FROM tp_custom_field_values_position;
DELETE FROM tp_cost_positions;
DELETE FROM tp_inbox_email_attachments;
DELETE FROM tp_inbox_email_read ;
DELETE FROM tp_inbox_emails; 
DELETE FROM tp_applicant_inbox_email_attachments;
DELETE FROM tp_applicant_inbox_emails;
DELETE FROM tp_applicant_documents;
DELETE FROM tp_messages_to;
DELETE FROM tp_messages;
DELETE FROM tp_applicants;
DELETE FROM tp_position_steps;
DELETE FROM tp_positions;
DELETE FROM tp_report_level_user WHERE user_id!=1;
DELETE FROM tp_user_permissions WHERE user_id!=1;
DELETE FROM tp_user_roles WHERE user_id!=1;
DELETE FROM tp_browser_import_session_documents;
DELETE FROM tp_bulk_import_session_custom_fields;
DELETE FROM tp_bulk_import_session_documents;
DELETE FROM tp_bulk_import_session_educational_info;
DELETE FROM tp_bulk_import_session_email_attachments;
DELETE FROM tp_bulk_import_session_result_educational_info;
DELETE FROM tp_bulk_import_session_result_skills;
DELETE FROM tp_bulk_import_session_results;
DELETE FROM tp_bulk_import_session_emails;
DELETE FROM tp_bulk_import_session_skills;
DELETE FROM tp_bulk_import_sessions;
DELETE FROM tp_recent_searches;
DELETE FROM tp_requisition_approval_steps_users WHERE user_id!=1;
DELETE FROM tp_costs;
DELETE FROM tp_users WHERE user_id!=1;

