package com.talentPool.customReports.dataobject;

// Generated Jan 5, 2012 7:05:07 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrColumnFilterMap generated by hbm2java
 */
@Entity
@Table(name = "tp_cr_column_filter_map")
public class CRColumnFilterMap implements java.io.Serializable {

	private Integer cfMapId;
	private CRFilters crFilters;	
	private String columnPropertyIds;

	public CRColumnFilterMap() {
	}

	public CRColumnFilterMap(CRFilters crFilters, String columnPropertyIds) {
		this.crFilters = crFilters;		
		this.columnPropertyIds = columnPropertyIds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cf_map_id", unique = true, nullable = false)
	public Integer getCfMapId() {
		return this.cfMapId;
	}

	public void setCfMapId(Integer cfMapId) {
		this.cfMapId = cfMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY, targetEntity=CRFilters.class)
	@JoinColumn(name = "filter_id",  nullable = false, referencedColumnName="filter_id")
	public CRFilters getCRFilters() {
		return this.crFilters;
	}

	public void setCRFilters(CRFilters crFilters) {
		this.crFilters = crFilters;
	}
		
	@Column(name = "column_property", nullable = false)
	public String getColumnPropertyIds() {
		return this.columnPropertyIds;
	}

	public void setColumnPropertyIds(String columnPropertyIds) {
		this.columnPropertyIds = columnPropertyIds;
	}

}