//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.07 at 04:57:03 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobPositionPosting complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobPositionPosting"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="JobAction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="JobType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="JobPositionPostingID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{}HiringOrg"/&gt;
 *         &lt;element ref="{}JobDisplayOptions"/&gt;
 *         &lt;element ref="{}JobPositionInformation"/&gt;
 *         &lt;element ref="{}HowToApply"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobPositionPosting", propOrder = {

})
public class JobPositionPosting
    implements Serializable
{

    @XmlElement(name = "JobAction", required = true)
    protected String jobAction;
    @XmlElement(name = "JobType", required = true)
    protected String jobType;
    @XmlElement(name = "JobPositionPostingID", required = true)
    protected String jobPositionPostingID;
    @XmlElement(name = "HiringOrg", required = true)
    protected HiringOrg hiringOrg;
    @XmlElement(name = "JobDisplayOptions", required = true)
    protected JobDisplayOptions jobDisplayOptions;
    @XmlElement(name = "JobPositionInformation", required = true)
    protected JobPositionInformation jobPositionInformation;
    @XmlElement(name = "HowToApply", required = true)
    protected HowToApply howToApply;

    /**
     * Gets the value of the jobAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobAction() {
        return jobAction;
    }

    /**
     * Sets the value of the jobAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobAction(String value) {
        this.jobAction = value;
    }

    /**
     * Gets the value of the jobType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * Sets the value of the jobType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobType(String value) {
        this.jobType = value;
    }

    /**
     * Gets the value of the jobPositionPostingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobPositionPostingID() {
        return jobPositionPostingID;
    }

    /**
     * Sets the value of the jobPositionPostingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobPositionPostingID(String value) {
        this.jobPositionPostingID = value;
    }

    /**
     * Gets the value of the hiringOrg property.
     * 
     * @return
     *     possible object is
     *     {@link HiringOrg }
     *     
     */
    public HiringOrg getHiringOrg() {
        return hiringOrg;
    }

    /**
     * Sets the value of the hiringOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link HiringOrg }
     *     
     */
    public void setHiringOrg(HiringOrg value) {
        this.hiringOrg = value;
    }

    /**
     * Gets the value of the jobDisplayOptions property.
     * 
     * @return
     *     possible object is
     *     {@link JobDisplayOptions }
     *     
     */
    public JobDisplayOptions getJobDisplayOptions() {
        return jobDisplayOptions;
    }

    /**
     * Sets the value of the jobDisplayOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobDisplayOptions }
     *     
     */
    public void setJobDisplayOptions(JobDisplayOptions value) {
        this.jobDisplayOptions = value;
    }

    /**
     * Gets the value of the jobPositionInformation property.
     * 
     * @return
     *     possible object is
     *     {@link JobPositionInformation }
     *     
     */
    public JobPositionInformation getJobPositionInformation() {
        return jobPositionInformation;
    }

    /**
     * Sets the value of the jobPositionInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPositionInformation }
     *     
     */
    public void setJobPositionInformation(JobPositionInformation value) {
        this.jobPositionInformation = value;
    }

    /**
     * Gets the value of the howToApply property.
     * 
     * @return
     *     possible object is
     *     {@link HowToApply }
     *     
     */
    public HowToApply getHowToApply() {
        return howToApply;
    }

    /**
     * Sets the value of the howToApply property.
     * 
     * @param value
     *     allowed object is
     *     {@link HowToApply }
     *     
     */
    public void setHowToApply(HowToApply value) {
        this.howToApply = value;
    }

}
