use talentpool;


DROP TABLE IF EXISTS proc_log;
create table proc_log(table_name varchar(50), column_name varchar(50), update_status int);
ALTER TABLE 	tp_application_properties	 MODIFY COLUMN 	application_property_value varchar(500);
alter table tp_users add column `time_zone` varchar(30) after force_password_change;


CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_announcements','date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_blacklist_history','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_documents','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_inbox_emails','email_date_send');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_inbox_emails','email_date_received');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_joining_history','joining_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_lookup_check','lookup_id_create_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_lookup_check','check_modified_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_selection_process','process_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_selection_process','process_moved_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicant_status_messages','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicants','applicant_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicants','applicant_date_joined');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicants','current_ctc_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicants','expected_ctc_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicants','resume_updated_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_applicants','resume_locked_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_application_properties_employee_portal','last_updated_on');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_application_properties_employee_portal','created_on');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments','appointment_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments','appointment_to_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments','appointment_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments','appointment_date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_to_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_from_date_new');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_to_date_new');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_processed_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_appointments_notifications','appointment_date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_audit_entries','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_browser_import_session_documents','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_budget_items','start_time');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_budget_items','end_time');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_budget_items','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_custom_fields','date_value');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_documents','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_emails','email_date_send');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_emails','email_date_received');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_emails','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_results','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_session_results','parsed_working_since');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_bulk_import_sessions','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_communications','communication_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_communications','communication_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_costs','cost_paid_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_costs','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_costs','cost_date_from');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_costs','cost_date_to');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_activity_summary','activity_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_activity_summary','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_candidate_master','applicant_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_candidate_master','applicant_date_joined');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_candidate_master','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_event_log','appointment_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_event_log','process_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_event_log','process_moved_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_event_log','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_event_summary','process_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_event_summary','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_last_update','last_run_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_hiring_summary','process_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_hiring_summary','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_master','position_date_expiry');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_master','position_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_master','position_date_approved');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_master','position_date_closed');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_position_master','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_scheduler','last_run_starttime');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_scheduler','last_run_endtime');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_scheduler','last_success_run');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_user_hiring_activity_summary','process_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_user_hiring_activity_summary','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_custom_field_values_applicant','date_value');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_custom_field_values_position','date_value');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_custom_field_values_position','date_value_to');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_custom_reports','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_custom_reports','date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_excel_import','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_excel_import_custom_field_values','date_value');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_feedback_forms','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_feedback_forms','last_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_flags','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_greytip_applicant_step_level_change','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_greytip_applicant_step_level_change','greytip_scheduler_run_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_inbox_emails','email_date_send');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_inbox_emails','email_date_received');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_inbox_folders','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_last_viewed','entity_date_viewed');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_messages','message_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_migration_show_message','flag_modified_on');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_migration_users','start_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_migration_users','last_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_migration_users','end_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_multiple_selects','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_offer_details_modified_interactions','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_offersheet_templates','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_on_step_level_change','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_on_step_level_change','scheduler_run_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_outbound','send_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_outbound','sent_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_position_documents','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_position_draft','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_position_social_posting_history','date_posted');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','position_date_expiry');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','position_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','position_date_closed');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','position_date_deleted');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','position_date_approved');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','position_publish_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','vendor_publish_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','vendor_publish_to_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','employee_publish_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','employee_publish_to_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','walk_in_publish_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','walk_in_publish_to_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','website_publish_from_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_positions','website_publish_to_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_ratings','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_recently_used_sources','time_used');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_release_info','date_of_installation');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_release_info','date_of_release');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_reminder','reminder_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_report_scheduler','start_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_report_scheduler','schedule_time');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_report_scheduler','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_report_templates','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_reports','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_requisition_approval_feedback','feedback_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_requisition_approval_steps','requisition_approval_step_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_requisition_approval_templates','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_salary_formulae','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_step_level','modified_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_step_master','date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_step_master','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_templates','template_date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_tmp_attachments','attachment_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_todo','appointment_time');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_todo','due_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_todo','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_user_activity','interaction_date');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_user_activity','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_user_hierarchy','date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_user_uuid_map','date_created');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_users','USER_LAST_LOGIN');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_users','password_date_modified');
CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_uuid_oauth_map','date_created');

CALL PROC_ALTER_COLUMN_TO_TIMESTAMP('tp_cr_scheduler','scheduler_start_hour');

ALTER TABLE tp_position_screen_description
	ADD COLUMN field_vendor_show CHAR(1) DEFAULT '0' NOT NULL AFTER field_position_mandatory, 
	ADD COLUMN field_vendor_rank TINYINT(4) NULL AFTER field_vendor_show, 
	ADD COLUMN field_employee_show CHAR(1) DEFAULT '0' NOT NULL AFTER field_vendor_rank,
	ADD COLUMN field_employee_rank TINYINT(4) NULL AFTER field_employee_show;
	
ALTER TABLE tp_position_screen_requirements
	ADD COLUMN field_vendor_show CHAR(1) DEFAULT '0' NOT NULL AFTER field_position_mandatory, 
	ADD COLUMN field_employee_show CHAR(1) DEFAULT '0' NOT NULL AFTER field_vendor_show;

DROP TABLE tp_user_information_shared;