//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 08:53:22 PM IST 
//


package com.talentPool.customReports.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for customReport complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="customReport">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReportName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReportSubCategory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Author" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportTemplate" type="{}tpReportTemplate"/>
 *         &lt;element name="ReportType" type="{}tpReportType"/>
 *         &lt;element name="CreationTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Columns" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Rows" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Measures" type="{}field" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="candNamesSpecifications" type="{}candNamesSpecifications"/>
 *         &lt;element name="ReportName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="showInactivePositions" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Filters" type="{}filters"/>
 *         &lt;element name="Datasets" type="{}datasetsType"/>
 *         &lt;element name="Datasource" type="{}datasourceType"/>
 *         &lt;element name="showRowGrandTotal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="LastModifiedTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reportId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="share" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "customReport", propOrder = {
    "reportName",
    "reportCategory",
    "reportSubCategory",
    "type",
    "description",
    "author",
    "reportTemplate",
    "reportType",
    "creationTime",
    "language",
    "columns",
    "rows",
    "measures",
    "candNamesSpecifications",
    "showInactivePositions",
    "reportFormat",
    "filters",
    "datasets",
    "datasource",
    "showRowGrandTotal",
    "lastModifiedTime"
})
public class CustomReport {

    @XmlElement(name = "ReportName", required = true)
    protected String reportName;
    @XmlElement(name = "ReportCategory", required = true)
    protected String reportCategory;
    @XmlElement(name = "ReportSubCategory", required = true)
    protected String reportSubCategory;
    @XmlElement(name = "Type", required = true)
    protected String type;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Author")
    protected String author;
    @XmlElement(name = "ReportTemplate", required = true)
    protected TpReportTemplate reportTemplate;
    @XmlElement(name = "ReportType", required = true)
    protected TpReportType reportType;
    @XmlElement(name = "CreationTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlElement(name = "Language")
    protected String language;
    @XmlElement(name = "Columns")
    protected List<Field> columns;
    @XmlElement(name = "Rows")
    protected List<Field> rows;
    @XmlElement(name = "Measures")
    protected List<Field> measures;
    @XmlElement(required = true)
    protected CandNamesSpecifications candNamesSpecifications;
    protected boolean showInactivePositions;
    @XmlElement(name = "ReportFormat", required = true)
    protected String reportFormat;
    @XmlElement(name = "Filters", required = true)
    protected Filters filters;
    @XmlElement(name = "Datasets", required = true)
    protected DatasetsType datasets;
    @XmlElement(name = "Datasource", required = true)
    protected DatasourceType datasource;
    protected boolean showRowGrandTotal;
    @XmlElement(name = "LastModifiedTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    @XmlAttribute(name = "reportId", required = true)
    protected String reportId;
    @XmlAttribute(name = "share", required = true)
    protected String share;

    /**
     * Gets the value of the reportName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * Sets the value of the reportName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportName(String value) {
        this.reportName = value;
    }

    /**
     * Gets the value of the reportCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportCategory() {
        return reportCategory;
    }

    /**
     * Sets the value of the reportCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportCategory(String value) {
        this.reportCategory = value;
    }

    /**
     * Gets the value of the reportSubCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportSubCategory() {
        return reportSubCategory;
    }

    /**
     * Sets the value of the reportSubCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportSubCategory(String value) {
        this.reportSubCategory = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the reportTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link TpReportTemplate }
     *     
     */
    public TpReportTemplate getReportTemplate() {
        return reportTemplate;
    }

    /**
     * Sets the value of the reportTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpReportTemplate }
     *     
     */
    public void setReportTemplate(TpReportTemplate value) {
        this.reportTemplate = value;
    }

    /**
     * Gets the value of the reportType property.
     * 
     * @return
     *     possible object is
     *     {@link TpReportType }
     *     
     */
    public TpReportType getReportType() {
        return reportType;
    }

    /**
     * Sets the value of the reportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TpReportType }
     *     
     */
    public void setReportType(TpReportType value) {
        this.reportType = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the columns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getColumns() {
        if (columns == null) {
            columns = new ArrayList<Field>();
        }
        return this.columns;
    }

    /**
     * Gets the value of the rows property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rows property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRows().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getRows() {
        if (rows == null) {
            rows = new ArrayList<Field>();
        }
        return this.rows;
    }

    /**
     * Gets the value of the measures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the measures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMeasures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getMeasures() {
        if (measures == null) {
            measures = new ArrayList<Field>();
        }
        return this.measures;
    }

    /**
     * Gets the value of the candNamesSpecifications property.
     * 
     * @return
     *     possible object is
     *     {@link CandNamesSpecifications }
     *     
     */
    public CandNamesSpecifications getCandNamesSpecifications() {
        return candNamesSpecifications;
    }

    /**
     * Sets the value of the candNamesSpecifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link CandNamesSpecifications }
     *     
     */
    public void setCandNamesSpecifications(CandNamesSpecifications value) {
        this.candNamesSpecifications = value;
    }

    /**
     * Gets the value of the reportFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportFormat() {
        return reportFormat;
    }

    /**
     * Sets the value of the reportFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportFormat(String value) {
        this.reportFormat = value;
    }

    /**
     * Gets the value of the filters property.
     * 
     * @return
     *     possible object is
     *     {@link Filters }
     *     
     */
    public Filters getFilters() {
        return filters;
    }

    /**
     * Sets the value of the filters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Filters }
     *     
     */
    public void setFilters(Filters value) {
        this.filters = value;
    }

    /**
     * Gets the value of the datasets property.
     * 
     * @return
     *     possible object is
     *     {@link DatasetsType }
     *     
     */
    public DatasetsType getDatasets() {
        return datasets;
    }

    /**
     * Sets the value of the datasets property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatasetsType }
     *     
     */
    public void setDatasets(DatasetsType value) {
        this.datasets = value;
    }

    /**
     * Gets the value of the datasource property.
     * 
     * @return
     *     possible object is
     *     {@link DatasourceType }
     *     
     */
    public DatasourceType getDatasource() {
        return datasource;
    }

    /**
     * Sets the value of the datasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatasourceType }
     *     
     */
    public void setDatasource(DatasourceType value) {
        this.datasource = value;
    }

    /**
     * Gets the value of the showRowGrandTotal property.
     * 
     */
    public boolean isShowRowGrandTotal() {
        return showRowGrandTotal;
    }

    /**
     * Sets the value of the showRowGrandTotal property.
     * 
     */
    public void setShowRowGrandTotal(boolean value) {
        this.showRowGrandTotal = value;
    }

    /**
     * Gets the value of the showInactivePositions property.
     * 
     */
    public boolean isShowInactivePositions() {
        return showInactivePositions;
    }

    /**
     * Sets the value of the showInactivePositions property.
     * 
     */
    public void setShowInactivePositions(boolean value) {
        this.showInactivePositions = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the reportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * Sets the value of the reportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportId(String value) {
        this.reportId = value;
    }

    /**
     * Gets the value of the share property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShare() {
        return share;
    }

    /**
     * Sets the value of the share property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShare(String value) {
        this.share = value;
    }

}
