//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobPositionInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobPositionInformation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="JobPositionTitle" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{}JobClassifications"/&gt;
 *         &lt;element ref="{}JobPositionDescription"/&gt;
 *         &lt;element ref="{}JobPositionRequirements"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobPositionInformation", propOrder = {

})
public class JobPositionInformation
    implements Serializable
{

    @XmlElement(name = "JobPositionTitle", required = true)
    protected String jobPositionTitle;
    @XmlElement(name = "JobClassifications", required = true)
    protected JobClassifications jobClassifications;
    @XmlElement(name = "JobPositionDescription", required = true)
    protected JobPositionDescription jobPositionDescription;
    @XmlElement(name = "JobPositionRequirements", required = true)
    protected JobPositionRequirements jobPositionRequirements;

    /**
     * Gets the value of the jobPositionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobPositionTitle() {
        return jobPositionTitle;
    }

    /**
     * Sets the value of the jobPositionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobPositionTitle(String value) {
        this.jobPositionTitle = value;
    }

    /**
     * Gets the value of the jobClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link JobClassifications }
     *     
     */
    public JobClassifications getJobClassifications() {
        return jobClassifications;
    }

    /**
     * Sets the value of the jobClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobClassifications }
     *     
     */
    public void setJobClassifications(JobClassifications value) {
        this.jobClassifications = value;
    }

    /**
     * Gets the value of the jobPositionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link JobPositionDescription }
     *     
     */
    public JobPositionDescription getJobPositionDescription() {
        return jobPositionDescription;
    }

    /**
     * Sets the value of the jobPositionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPositionDescription }
     *     
     */
    public void setJobPositionDescription(JobPositionDescription value) {
        this.jobPositionDescription = value;
    }

    /**
     * Gets the value of the jobPositionRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link JobPositionRequirements }
     *     
     */
    public JobPositionRequirements getJobPositionRequirements() {
        return jobPositionRequirements;
    }

    /**
     * Sets the value of the jobPositionRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPositionRequirements }
     *     
     */
    public void setJobPositionRequirements(JobPositionRequirements value) {
        this.jobPositionRequirements = value;
    }

}
