//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApplicationMethods complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationMethods"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}ByEmail"/&gt;
 *         &lt;element ref="{}ByWeb"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationMethods", propOrder = {

})
public class ApplicationMethods
    implements Serializable
{

    @XmlElement(name = "ByEmail", required = true)
    protected ByEmail byEmail;
    @XmlElement(name = "ByWeb", required = true)
    protected ByWeb byWeb;

    /**
     * Gets the value of the byEmail property.
     * 
     * @return
     *     possible object is
     *     {@link ByEmail }
     *     
     */
    public ByEmail getByEmail() {
        return byEmail;
    }

    /**
     * Sets the value of the byEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ByEmail }
     *     
     */
    public void setByEmail(ByEmail value) {
        this.byEmail = value;
    }

    /**
     * Gets the value of the byWeb property.
     * 
     * @return
     *     possible object is
     *     {@link ByWeb }
     *     
     */
    public ByWeb getByWeb() {
        return byWeb;
    }

    /**
     * Sets the value of the byWeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link ByWeb }
     *     
     */
    public void setByWeb(ByWeb value) {
        this.byWeb = value;
    }

}
