//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompensationDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompensationDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}Pay"/&gt;
 *         &lt;element name="BenifitsDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompensationDescription", propOrder = {

})
public class CompensationDescription
    implements Serializable
{

    @XmlElement(name = "Pay", required = true)
    protected Pay pay;
    @XmlElement(name = "BenifitsDescription", required = true)
    protected String benifitsDescription;

    /**
     * Gets the value of the pay property.
     * 
     * @return
     *     possible object is
     *     {@link Pay }
     *     
     */
    public Pay getPay() {
        return pay;
    }

    /**
     * Sets the value of the pay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pay }
     *     
     */
    public void setPay(Pay value) {
        this.pay = value;
    }

    /**
     * Gets the value of the benifitsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenifitsDescription() {
        return benifitsDescription;
    }

    /**
     * Sets the value of the benifitsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenifitsDescription(String value) {
        this.benifitsDescription = value;
    }

}
