//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobExperience complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobExperience"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="MinimumExperience" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MaximumExperience" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobExperience", propOrder = {

})
public class JobExperience
    implements Serializable
{

    @XmlElement(name = "MinimumExperience", required = true)
    protected String minimumExperience;
    @XmlElement(name = "MaximumExperience", required = true)
    protected String maximumExperience;

    /**
     * Gets the value of the minimumExperience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumExperience() {
        return minimumExperience;
    }

    /**
     * Sets the value of the minimumExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumExperience(String value) {
        this.minimumExperience = value;
    }

    /**
     * Gets the value of the maximumExperience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumExperience() {
        return maximumExperience;
    }

    /**
     * Sets the value of the maximumExperience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumExperience(String value) {
        this.maximumExperience = value;
    }

}
