//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobPositionDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobPositionDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="JobKeywords" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{}JobPositionLocation"/&gt;
 *         &lt;element ref="{}CompensationDescription"/&gt;
 *         &lt;element name="SummaryText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobPositionDescription", propOrder = {

})
public class JobPositionDescription
    implements Serializable
{

    @XmlElement(name = "JobKeywords", required = true)
    protected String jobKeywords;
    @XmlElement(name = "JobPositionLocation", required = true)
    protected JobPositionLocation jobPositionLocation;
    @XmlElement(name = "CompensationDescription", required = true)
    protected CompensationDescription compensationDescription;
    @XmlElement(name = "SummaryText", required = true)
    protected String summaryText;

    /**
     * Gets the value of the jobKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobKeywords() {
        return jobKeywords;
    }

    /**
     * Sets the value of the jobKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobKeywords(String value) {
        this.jobKeywords = value;
    }

    /**
     * Gets the value of the jobPositionLocation property.
     * 
     * @return
     *     possible object is
     *     {@link JobPositionLocation }
     *     
     */
    public JobPositionLocation getJobPositionLocation() {
        return jobPositionLocation;
    }

    /**
     * Sets the value of the jobPositionLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPositionLocation }
     *     
     */
    public void setJobPositionLocation(JobPositionLocation value) {
        this.jobPositionLocation = value;
    }

    /**
     * Gets the value of the compensationDescription property.
     * 
     * @return
     *     possible object is
     *     {@link CompensationDescription }
     *     
     */
    public CompensationDescription getCompensationDescription() {
        return compensationDescription;
    }

    /**
     * Sets the value of the compensationDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensationDescription }
     *     
     */
    public void setCompensationDescription(CompensationDescription value) {
        this.compensationDescription = value;
    }

    /**
     * Gets the value of the summaryText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryText() {
        return summaryText;
    }

    /**
     * Sets the value of the summaryText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryText(String value) {
        this.summaryText = value;
    }

}
