//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:52:02 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobPositionPostings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobPositionPostings"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{}JobPositionPosting"/&gt;
 *         &lt;element name="JobFeedResponseEmail" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "JobPositionPostings")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobPositionPostings", propOrder = {

})
public class JobPositionPostings
    implements Serializable
{

    @XmlElement(name = "JobPositionPosting", required = true)
    protected JobPositionPosting jobPositionPosting;
    @XmlElement(name = "JobFeedResponseEmail", required = true)
    protected String jobFeedResponseEmail;

    /**
     * Gets the value of the jobPositionPosting property.
     * 
     * @return
     *     possible object is
     *     {@link JobPositionPosting }
     *     
     */
    public JobPositionPosting getJobPositionPosting() {
        return jobPositionPosting;
    }

    /**
     * Sets the value of the jobPositionPosting property.
     * 
     * @param value
     *     allowed object is
     *     {@link JobPositionPosting }
     *     
     */
    public void setJobPositionPosting(JobPositionPosting value) {
        this.jobPositionPosting = value;
    }

    /**
     * Gets the value of the jobFeedResponseEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobFeedResponseEmail() {
        return jobFeedResponseEmail;
    }

    /**
     * Sets the value of the jobFeedResponseEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobFeedResponseEmail(String value) {
        this.jobFeedResponseEmail = value;
    }

}
