//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobQualifications complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobQualifications"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="UGQualifications" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="UGSpecializations" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PGQualifications" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PGSpecializations" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DoctorateQualifications" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DoctorateSpecializations" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobQualifications", propOrder = {

})
public class JobQualifications
    implements Serializable
{

    @XmlElement(name = "UGQualifications", required = true)
    protected String ugQualifications;
    @XmlElement(name = "UGSpecializations", required = true)
    protected String ugSpecializations;
    @XmlElement(name = "PGQualifications", required = true)
    protected String pgQualifications;
    @XmlElement(name = "PGSpecializations", required = true)
    protected String pgSpecializations;
    @XmlElement(name = "DoctorateQualifications", required = true)
    protected String doctorateQualifications;
    @XmlElement(name = "DoctorateSpecializations", required = true)
    protected String doctorateSpecializations;

    /**
     * Gets the value of the ugQualifications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUGQualifications() {
        return ugQualifications;
    }

    /**
     * Sets the value of the ugQualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUGQualifications(String value) {
        this.ugQualifications = value;
    }

    /**
     * Gets the value of the ugSpecializations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUGSpecializations() {
        return ugSpecializations;
    }

    /**
     * Sets the value of the ugSpecializations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUGSpecializations(String value) {
        this.ugSpecializations = value;
    }

    /**
     * Gets the value of the pgQualifications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPGQualifications() {
        return pgQualifications;
    }

    /**
     * Sets the value of the pgQualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPGQualifications(String value) {
        this.pgQualifications = value;
    }

    /**
     * Gets the value of the pgSpecializations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPGSpecializations() {
        return pgSpecializations;
    }

    /**
     * Sets the value of the pgSpecializations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPGSpecializations(String value) {
        this.pgSpecializations = value;
    }

    /**
     * Gets the value of the doctorateQualifications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorateQualifications() {
        return doctorateQualifications;
    }

    /**
     * Sets the value of the doctorateQualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorateQualifications(String value) {
        this.doctorateQualifications = value;
    }

    /**
     * Gets the value of the doctorateSpecializations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoctorateSpecializations() {
        return doctorateSpecializations;
    }

    /**
     * Sets the value of the doctorateSpecializations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoctorateSpecializations(String value) {
        this.doctorateSpecializations = value;
    }

}
