//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimaryJobCategory complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrimaryJobCategory"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="JobIndustryCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="JobFunctionCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="JobRoleCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrimaryJobCategory", propOrder = {

})
public class PrimaryJobCategory
    implements Serializable
{

    @XmlElement(name = "JobIndustryCode", required = true)
    protected String jobIndustryCode;
    @XmlElement(name = "JobFunctionCode", required = true)
    protected String jobFunctionCode;
    @XmlElement(name = "JobRoleCode", required = true)
    protected String jobRoleCode;

    /**
     * Gets the value of the jobIndustryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobIndustryCode() {
        return jobIndustryCode;
    }

    /**
     * Sets the value of the jobIndustryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobIndustryCode(String value) {
        this.jobIndustryCode = value;
    }

    /**
     * Gets the value of the jobFunctionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobFunctionCode() {
        return jobFunctionCode;
    }

    /**
     * Sets the value of the jobFunctionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobFunctionCode(String value) {
        this.jobFunctionCode = value;
    }

    /**
     * Gets the value of the jobRoleCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobRoleCode() {
        return jobRoleCode;
    }

    /**
     * Sets the value of the jobRoleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobRoleCode(String value) {
        this.jobRoleCode = value;
    }

}
