//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 08:53:22 PM IST 
//


package com.talentPool.customReports.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="field">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tableType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fieldValueType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dbName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="witdh" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="binding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dataType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefaultValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AllowBlank" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Visible" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UsedInQuery" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="ShowSubTotal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="CellContent">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="simplecount"/>
 *               &lt;enumeration value="multiple"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CellContentFormat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="inline"/>
 *               &lt;enumeration value="blowout"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "field", propOrder = {
    "key",
    "category",
    "tableType",
    "fieldValueType",
    "displayName",
    "dbName",
    "witdh",
    "binding",
    "dataType",
    "defaultValue",
    "allowBlank",
    "visible",
    "usedInQuery",
    "showSubTotal",
    "cellContent",
    "cellContentFormat"
})
public class Field {

    @XmlElement(required = true)
    protected String key;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected String tableType;
    @XmlElement(required = true)
    protected String fieldValueType;
    @XmlElement(required = true)
    protected String displayName;
    @XmlElement(required = true)
    protected String dbName;
    protected int witdh;
    protected String binding;
    @XmlElement(required = true)
    protected String dataType;
    @XmlElement(name = "DefaultValue")
    protected String defaultValue;
    @XmlElement(name = "AllowBlank")
    protected Boolean allowBlank;
    @XmlElement(name = "Visible")
    protected Boolean visible;
    @XmlElement(name = "UsedInQuery")
    protected Object usedInQuery;
    @XmlElement(name = "ShowSubTotal")
    protected boolean showSubTotal;
    @XmlElement(name = "CellContent", required = true)
    protected String cellContent;
    @XmlElement(name = "CellContentFormat", required = true)
    protected String cellContentFormat;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the tableType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * Sets the value of the tableType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableType(String value) {
        this.tableType = value;
    }

    /**
     * Gets the value of the fieldValueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldValueType() {
        return fieldValueType;
    }

    /**
     * Sets the value of the fieldValueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldValueType(String value) {
        this.fieldValueType = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the dbName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * Sets the value of the dbName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbName(String value) {
        this.dbName = value;
    }

    /**
     * Gets the value of the witdh property.
     * 
     */
    public int getWitdh() {
        return witdh;
    }

    /**
     * Sets the value of the witdh property.
     * 
     */
    public void setWitdh(int value) {
        this.witdh = value;
    }

    /**
     * Gets the value of the binding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinding() {
        return binding;
    }

    /**
     * Sets the value of the binding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinding(String value) {
        this.binding = value;
    }

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataType(String value) {
        this.dataType = value;
    }

    /**
     * Gets the value of the defaultValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * Sets the value of the defaultValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultValue(String value) {
        this.defaultValue = value;
    }

    /**
     * Gets the value of the allowBlank property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowBlank() {
        return allowBlank;
    }

    /**
     * Sets the value of the allowBlank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowBlank(Boolean value) {
        this.allowBlank = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVisible() {
        return visible;
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the usedInQuery property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUsedInQuery() {
        return usedInQuery;
    }

    /**
     * Sets the value of the usedInQuery property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUsedInQuery(Object value) {
        this.usedInQuery = value;
    }

    /**
     * Gets the value of the showSubTotal property.
     * 
     */
    public boolean isShowSubTotal() {
        return showSubTotal;
    }

    /**
     * Sets the value of the showSubTotal property.
     * 
     */
    public void setShowSubTotal(boolean value) {
        this.showSubTotal = value;
    }

    /**
     * Gets the value of the cellContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellContent() {
        return cellContent;
    }

    /**
     * Sets the value of the cellContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellContent(String value) {
        this.cellContent = value;
    }

    /**
     * Gets the value of the cellContentFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellContentFormat() {
        return cellContentFormat;
    }

    /**
     * Sets the value of the cellContentFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellContentFormat(String value) {
        this.cellContentFormat = value;
    }

}
