//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 08:53:22 PM IST 
//


package com.talentPool.customReports.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.talentPool.customReports.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Report_QNAME = new QName("", "report");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.talentPool.customReports.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustomReport }
     * 
     */
    public CustomReport createCustomReport() {
        return new CustomReport();
    }

    /**
     * Create an instance of {@link DatasourceType }
     * 
     */
    public DatasourceType createDatasourceType() {
        return new DatasourceType();
    }

    /**
     * Create an instance of {@link DatasetsType }
     * 
     */
    public DatasetsType createDatasetsType() {
        return new DatasetsType();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link TpReportType }
     * 
     */
    public TpReportType createTpReportType() {
        return new TpReportType();
    }

    /**
     * Create an instance of {@link DatasetType }
     * 
     */
    public DatasetType createDatasetType() {
        return new DatasetType();
    }

    /**
     * Create an instance of {@link TpReportTemplate }
     * 
     */
    public TpReportTemplate createTpReportTemplate() {
        return new TpReportTemplate();
    }

    /**
     * Create an instance of {@link Filters }
     * 
     */
    public Filters createFilters() {
        return new Filters();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link CandNamesSpecifications }
     * 
     */
    public CandNamesSpecifications createCandNamesSpecifications() {
        return new CandNamesSpecifications();
    }

    /**
     * Create an instance of {@link ReportFormatType }
     * 
     */
    public ReportFormatType createReportFormatType() {
        return new ReportFormatType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomReport }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "report")
    public JAXBElement<CustomReport> createReport(CustomReport value) {
        return new JAXBElement<CustomReport>(_Report_QNAME, CustomReport.class, null, value);
    }

}
