package com.talentPool.customReports.dataobject;

// Generated Mar 12, 2012 2:51:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CRReportTypeColumnMapping generated by hbm2java
 */
@Entity
@Table(name = "tp_cr_report_type_column_mapping")
public class CRReportTypeColumnMapping implements java.io.Serializable {

	private CRReportTypeColumnMappingId id;
	private CRReportTypes crReportTypes;
	private CRColumn customReportColumns;

	public CRReportTypeColumnMapping() {
	}

	public CRReportTypeColumnMapping(CRReportTypeColumnMappingId id,
			CRReportTypes crReportTypes,
			CRColumn customReportColumns) {
		this.id = id;
		this.crReportTypes = crReportTypes;
		this.customReportColumns = customReportColumns;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "crReportTypeId", column = @Column(name = "cr_report_type_id", nullable = false)),
			@AttributeOverride(name = "columnProperty", column = @Column(name = "column_property", nullable = false)) })
	public CRReportTypeColumnMappingId getId() {
		return this.id;
	}

	public void setId(CRReportTypeColumnMappingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cr_report_type_id", nullable = false, insertable = false, updatable = false)
	public CRReportTypes getCrReportTypes() {
		return this.crReportTypes;
	}

	public void setCrReportTypes(CRReportTypes crReportTypes) {
		this.crReportTypes = crReportTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "column_property", nullable = false, insertable = false, updatable = false, referencedColumnName="column_property")
	public CRColumn getCustomReportColumns() {
		return this.customReportColumns;
	}

	public void setCustomReportColumns(
			CRColumn customReportColumns) {
		this.customReportColumns = customReportColumns;
	}

}
