//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.05 at 04:29:13 PM IST 
//


package com.talentPool.positions.dataobject;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JobPositionLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="JobPositionLocation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="InterNationalLoc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InterNationalLocOther" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IndianLoc" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IndianLocOther" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JobPositionLocation", propOrder = {

})
public class JobPositionLocation
    implements Serializable
{

    @XmlElement(name = "InterNationalLoc", required = true)
    protected String interNationalLoc;
    @XmlElement(name = "InterNationalLocOther", required = true)
    protected String interNationalLocOther;
    @XmlElement(name = "IndianLoc", required = true)
    protected String indianLoc;
    @XmlElement(name = "IndianLocOther", required = true)
    protected String indianLocOther;

    /**
     * Gets the value of the interNationalLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterNationalLoc() {
        return interNationalLoc;
    }

    /**
     * Sets the value of the interNationalLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterNationalLoc(String value) {
        this.interNationalLoc = value;
    }

    /**
     * Gets the value of the interNationalLocOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterNationalLocOther() {
        return interNationalLocOther;
    }

    /**
     * Sets the value of the interNationalLocOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterNationalLocOther(String value) {
        this.interNationalLocOther = value;
    }

    /**
     * Gets the value of the indianLoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndianLoc() {
        return indianLoc;
    }

    /**
     * Sets the value of the indianLoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndianLoc(String value) {
        this.indianLoc = value;
    }

    /**
     * Gets the value of the indianLocOther property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndianLocOther() {
        return indianLocOther;
    }

    /**
     * Sets the value of the indianLocOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndianLocOther(String value) {
        this.indianLocOther = value;
    }

}
