//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 08:53:22 PM IST 
//


package com.talentPool.customReports.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for candNamesSpecifications complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="candNamesSpecifications">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="showNames" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="extraCandidateAttributes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stepsToShowNames" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stepsToShowNamesAndAttributes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "candNamesSpecifications", propOrder = {
    "showNames",
    "extraCandidateAttributes",
    "stepsToShowNames",
    "stepsToShowNamesAndAttributes"
})
public class CandNamesSpecifications {

    protected boolean showNames;
    @XmlElement(required = true)
    protected String extraCandidateAttributes;
    @XmlElement(required = true)
    protected String stepsToShowNames;
    @XmlElement(required = true)
    protected String stepsToShowNamesAndAttributes;

    /**
     * Gets the value of the showNames property.
     * 
     */
    public boolean isShowNames() {
        return showNames;
    }

    /**
     * Sets the value of the showNames property.
     * 
     */
    public void setShowNames(boolean value) {
        this.showNames = value;
    }

    /**
     * Gets the value of the extraCandidateAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraCandidateAttributes() {
        return extraCandidateAttributes;
    }

    /**
     * Sets the value of the extraCandidateAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraCandidateAttributes(String value) {
        this.extraCandidateAttributes = value;
    }

    /**
     * Gets the value of the stepsToShowNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepsToShowNames() {
        return stepsToShowNames;
    }

    /**
     * Sets the value of the stepsToShowNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepsToShowNames(String value) {
        this.stepsToShowNames = value;
    }

    /**
     * Gets the value of the stepsToShowNamesAndAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStepsToShowNamesAndAttributes() {
        return stepsToShowNamesAndAttributes;
    }

    /**
     * Sets the value of the stepsToShowNamesAndAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStepsToShowNamesAndAttributes(String value) {
        this.stepsToShowNamesAndAttributes = value;
    }

}
