
http.server=http://api.recaptcha.net
https.server=https://api-secure.recaptcha.net
private.key=6LfevgsAAAAAAEd9cuSKT6FWineMDruc90sqXotk
public.key=6LfevgsAAAAAAEbwheLjO1Zj8jHwruRkHTBpFfxQ
verify.url=http://api-verify.recaptcha.net/verify