package com.talentPool.customReports.dataobject;

// Generated Mar 12, 2012 2:51:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CRReportTypeColumnMappingId generated by hbm2java
 */
@Embeddable
public class CRReportTypeColumnMappingId implements java.io.Serializable {

	private long crReportTypeId;
	private String columnProperty;

	public CRReportTypeColumnMappingId() {
	}

	public CRReportTypeColumnMappingId(long crReportTypeId,
			String columnProperty) {
		this.crReportTypeId = crReportTypeId;
		this.columnProperty = columnProperty;
	}

	@Column(name = "cr_report_type_id", nullable = false)
	public long getCrReportTypeId() {
		return this.crReportTypeId;
	}

	public void setCrReportTypeId(long crReportTypeId) {
		this.crReportTypeId = crReportTypeId;
	}

	@Column(name = "column_property", nullable = false)
	public String getColumnProperty() {
		return this.columnProperty;
	}

	public void setColumnProperty(String columnProperty) {
		this.columnProperty = columnProperty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CRReportTypeColumnMappingId))
			return false;
		CRReportTypeColumnMappingId castOther = (CRReportTypeColumnMappingId) other;

		return (this.getCrReportTypeId() == castOther.getCrReportTypeId())
				&& ((this.getColumnProperty() == castOther.getColumnProperty()) || (this
						.getColumnProperty() != null
						&& castOther.getColumnProperty() != null && this
						.getColumnProperty().equals(
								castOther.getColumnProperty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCrReportTypeId();
		result = 37
				* result
				+ (getColumnProperty() == null ? 0 : this.getColumnProperty()
						.hashCode());
		return result;
	}

}
