package com.talentPool.masters.dataobject;
// Generated Apr 26, 2012 2:09:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TpDesignationsAliases generated by hbm2java
 */
@Entity
@Table(name = "tp_designations_aliases", uniqueConstraints = @UniqueConstraint(columnNames = "alias"))
public class DesignationAliasesData implements java.io.Serializable {

	private DesignationAliasesId id;
	private DesignationsData designationsData;

	public DesignationAliasesData() {
	}

	public DesignationAliasesData(DesignationAliasesId id,
			DesignationsData designationsData) {
		this.id = id;
		this.designationsData = designationsData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "designationId", column = @Column(name = "designation_id", nullable = false)),
			@AttributeOverride(name = "alias", column = @Column(name = "alias", unique = true, nullable = false, length = 150)) })
	public DesignationAliasesId getId() {
		return this.id;
	}

	public void setId(DesignationAliasesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "designation_id", nullable = false, insertable = false, updatable = false)
	public DesignationsData getDesignationsData() {
		return this.designationsData;
	}

	public void setDesignationsData(DesignationsData designationsData) {
		this.designationsData = designationsData;
	}

}
