package com.talentPool.masters.dataobject;
// Generated Apr 26, 2012 2:09:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TpDesignations generated by hbm2java
 */
@Entity
@Table(name = "tp_designations", uniqueConstraints = @UniqueConstraint(columnNames = "designation_name"))
public class DesignationsData implements java.io.Serializable {

	private Long designationId;
	private String designationName;
	private Set<DesignationAliasesData> designationsAliasesesData = new HashSet<DesignationAliasesData>(0);

	public DesignationsData() {
	}

	public DesignationsData(String designationName) {
		this.designationName = designationName;
	}

	public DesignationsData(String designationName,
			Set<DesignationAliasesData> designationsAliasesesData) {
		this.designationName = designationName;
		this.designationsAliasesesData = designationsAliasesesData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "designation_id", unique = true, nullable = false)
	public Long getDesignationId() {
		return this.designationId;
	}

	public void setDesignationId(Long designationId) {
		this.designationId = designationId;
	}

	@Column(name = "designation_name", unique = true, nullable = false, length = 150)
	public String getDesignationName() {
		return this.designationName;
	}

	public void setDesignationName(String designationName) {
		this.designationName = designationName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "designationsData")
	public Set<DesignationAliasesData> getDesignationsAliasesesData() {
		return this.designationsAliasesesData;
	}

	public void setDesignationsAliasesesData(Set<DesignationAliasesData> designationsAliasesesData) {
		this.designationsAliasesesData = designationsAliasesesData;
	}

}
