package com.talentPool.masters.dataobject;
// Generated Apr 26, 2012 2:09:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TpEmployers generated by hbm2java
 */
@Entity
@Table(name = "tp_employers", uniqueConstraints = @UniqueConstraint(columnNames = "employer_name"))
public class EmployersData implements java.io.Serializable {

	private Long employerId;
	private String employerName;
	private Set<EmployerAliasesData> employerAliasesesData = new HashSet<EmployerAliasesData>(0);

	public EmployersData() {
	}

	public EmployersData(String employerName) {
		this.employerName = employerName;
	}

	public EmployersData(String employerName, Set<EmployerAliasesData> employerAliasesesData) {
		this.employerName = employerName;
		this.employerAliasesesData = employerAliasesesData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "employer_id", unique = true, nullable = false)
	public Long getEmployerId() {
		return this.employerId;
	}

	public void setEmployerId(Long employerId) {
		this.employerId = employerId;
	}

	@Column(name = "employer_name", unique = true, nullable = false, length = 150)
	public String getEmployerName() {
		return this.employerName;
	}

	public void setEmployerName(String employerName) {
		this.employerName = employerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employersData")
	public Set<EmployerAliasesData> getEmployerAliasesesData() {
		return this.employerAliasesesData;
	}

	public void setEmployerAliasesesData(Set<EmployerAliasesData> employerAliasesesData) {
		this.employerAliasesesData = employerAliasesesData;
	}
}