package com.talentPool.masters.dataobject;
// Generated Apr 26, 2012 2:09:11 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TpEmployerAliases generated by hbm2java
 */
@Entity
@Table(name = "tp_employer_aliases", uniqueConstraints = @UniqueConstraint(columnNames = "alias"))
public class EmployerAliasesData implements java.io.Serializable {

	private EmployerAliasesId id;
	private EmployersData employersData;

	public EmployerAliasesData() {
	}

	public EmployerAliasesData(EmployerAliasesId id, EmployersData employersData) {
		this.id = id;
		this.employersData = employersData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "employerId", column = @Column(name = "employer_id", nullable = false)),
			@AttributeOverride(name = "alias", column = @Column(name = "alias", unique = true, nullable = false, length = 150)) })
	public EmployerAliasesId getId() {
		return this.id;
	}

	public void setId(EmployerAliasesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employer_id", nullable = false, insertable = false, updatable = false)
	public EmployersData getEmployersData() {
		return this.employersData;
	}

	public void setEmployersData(EmployersData employersData) {
		this.employersData = employersData;
	}
}