########## Property Contains the Reg Expression used in parsing the Resume got from Naukri. ##########

naukriFormatExp3	= (?mids)(Current Location.*)(Functional Area.*)(Role.*)(Industry.*)
naukriFormatExp4	= (?mids)(Download Save.*)(To FolderContact.*)(Send Mail.*)(Send SMSForward Print.*)
part31 				= (?m)(Commented by: CommentAuthor on CommentTime.*)
part35 				= (?mids)(Send Email.*)
part28 				= (?mids)(Last Active:.*)
part44				= Comment
part45				= Remaining
part46				= Characters
part47 				= Preview
part48 				= ModifyForward Print
part49 				= ModifySMS Forward Print

########## Used to parse Naukri Phone:(?mids)(View/Add.*)
part40 				= (?mids)(Phone:)(.*)

########## Used To Parse Source
part13				= naukri

########## Used to Parse Education Details
part25				= (?mids)(Education.*)
part41 				= Education
part22 				= IT Skills and Projects
part23 				= Work Authorization
part24 				= Candidate Text Resume
part38 				= IT Skills
part17 				= (?mids).*?from.*?in.*?[0-9]{4}
part18 				= (?mids)from(.*)? in 

########## Used for Parse Applicant Current CTC
part26 				= (?mids)(Annual Salary\\s:)(.*)
part34 				= (Annual Salary.*)

########## Used To Parse Work Experience
part39 				= (?mids)(Total Experience:)(.*)
part33 				= (?mids)(Work Experience)(.*)

########## Used To Parse Current Employer
part36 				= (?mids)(Current Company.*)

########## Used To Parse Current Location
part37 				= (Current Location.*)

########## Other Parameters used to parse
NotDisclosed 		= Not Disclosed
AnnualSalary 		= Annual Salary:
CurrentLocation 	= Current Location:
CurrentCompany 		= Current Company: