!define VERSION 'v16.2.0'
!define PRODUCT_NAME 'TalentPool'
!define COMPANY_NAME 'Nitman'
!define DRIVE_NAME 'C:'
!define SETUP_FILE 'talentpool.exe'
!define JRE_FILE 'softwares\jre-7u79-windows-i586.exe'
!define JRE_FILE_64 'softwares\jre-7u79-windows-x64.exe'
!define REQUIRED_JRE_VERSION '1.7.0_79'
!define REQUIRED_JRE_VERSION_64 '1.7.0_79'
!define APP_SERVER_FILE_PATH 'softwares\apache-tomcat-7.0.22-windows-x86.zip'
!define APP_SERVER_FILE_ZIP 'apache-tomcat-7.0.22-windows-x86.zip'
!define APP_SERVER_FILE_PATH_64 'softwares\apache-tomcat-7.0.22-windows-x64.zip'
!define APP_SERVER_FILE_ZIP_64 'apache-tomcat-7.0.22-windows-x64.zip'
!define APP_SERVER_FILE 'apache-tomcat-7.0.22'
!define LICENSE_FILE 'EULA.rtf'
!define LICENSE_FILE_DIR 'license'
!define SERVICE_NAME 'MySQL1234'
!define SERVICE_NAME1 'MySQL7'
!define DB_SCRIPT_FILE 'dbscripts\allScripts.sql'
!define DB_SCRIPT_DIR 'dbscripts'
!define BENCHMARK_DIR 'NLPParser'
!define MYSQL_CREATE_USER_SQL 'createMySQLUser.sql'
!define MYSQL_REMOVE_SUPER_PRIVILEGE 'removeSuperPrivilege.sql'
!define MYSQL_SETUP 'softwares\server_577_rc_winx64.msi'
!define MYSQL_SETUP1 'softwares\server_577_rc_win32.msi'
!define MYSQL_SETUP2 'softwares\mysql-essential-5.0.18-win32.msi'
!define TALENTPOOL_SERVICE 'TalentPool'
!define PLUGIN_DIR 'plugins'
!define QUARTZ_DB_PASSWORD_PROPERTY 'org.quartz.dataSource.myDS.password='
!define SETUP_ICON 'setup.ico'
!define UNINSTALL_ICON 'uninstall.ico'
!define TALENTPOOL_ICON 'talentpool.ico'
!define TALENTPOOL_BITMAP 'win-green.bmp'
!define REPORTS_DIR 'reports'
!define CUSTOM_REPORTS_DIR 'customReports'
!define JNI_DIR 'jni'
!define TEMPLATES_DIR 'templates'
!define LOG_DIR 'logs'
!define BACKUP_DIR 'backup'
!define CONFIG_DIR 'config'
!define HELP_DIR 'help'
!define DOCUMENTS_DIR 'documents'
!define TALENTPOOL_PROPERTIES 'TalentPool.properties'
!define TALENTPOOL_LABELS_PROPERTIES 'talentpoollabels.properties'
!define OTHER_APPLICATION_PROPERTIES 'OtherApplication.properties'
!define INSTALLATION_KEY_GENERATOR 'installationKeyGenerator.jar'
!define DB_USERNAME_PROPERTY 'db.username'
!define DB_PASSWORD_PROPERTY 'db.password'
!define DB_USERNAME 'nitman'
!define DB_PASSWORD 'N!tm@n'
!define PROPERTIES_MERGER 'mergeProperties.jar'
!define DBUTIL 'decryptProperties.jar'
!define BACKUP_UTIL 'backup.bat'
!define RESTORE_UTIL 'restore.bat'
!define RESTORE_DB_UTIL 'restoreDB.bat'
!define MERGE_ATT_TO_DOCS_UTIL 'mergeAttachmentsToDocuments.bat'
!define INSTALL_LOG 'install.log'
!define ICONS_DIR 'icons'
!define OTHERS_DIR 'others'
!define DEMODATA_DIR 'demodata'
!define JAVA_HEAP_SPACE '1024'
!define MAX_PERM_SIZE '128m'
!define SECURITY_FILE1 'softwares\securityLib\local_policy.jar'
!define SECURITY_FILE2 'softwares\securityLib\US_export_policy.jar'